language: generic
sudo: required
service:
  - docker

before_install: 
  - docker build -t cenkay/react-test -f ./client/Dockerfile.dev ./client 


script:
  - docker run -e CI=true cenkay/react-test npm test

after_success:
  - docker build -t cenkay/multi-client ./client
  - docker build -t cenkay/multi-nginx ./nginx
  - docker build -t cenkay/multi-server ./server
  - docker build -t cenkay/multi-worker ./worker
  # Login to the Docker CLI
  - docker login docker.io -u $DOCKER_ID -p $DOCKER_PASSWORD
  # Take those images and push them to docker hub
  - docker push cenkay/multi-client
  - docker push cenkay/multi-nginx
  - docker push cenkay/multi-server
  - docker push cenkay/multi-worker

