language: generic
sudo: required
service:
  - docker

before_install: 
  - docker build -t cnkay/react-test -f ./client/Dockerfile.dev ./client 


script:
  - docker run -c CI=true cnkay/react-test npm test

after_success:
  - docker build -t cnkay/multi-client ./client
  - docker build -t cnkay/multi-nginx ./nginx
  - docker build -t cnkay/multi-server ./server
  - docker build -t cnkay/multi-worker ./worker
  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub